### ISSUE TITLE
Imparius grove causing crashes

### ISSUE THREAD

**Issue by AsureusGalactica** [CorgiTaco-MC/CorgiLib#17]
I have the most recent versions of Geckolib, Corgilib, and Biomes You'll Go, and it's saying that the crash is from the tree 

NBT feature thing 

[crash-2023-06-15_02.21.50-server.txt](https://github.com/CorgiTaco/CorgiLib/files/11754302/crash-2023-06-15_02.21.50-server.txt)
Here is the crashlog

**Comment by CorgiTaco** [comment]
This issue is rooted in BYG, please report it to that issue tracker.
