### ISSUE TITLE
Error Loading mods

### ISSUE THREAD

**Issue by CatPrinceLu** [CorgiTaco-MC/CorgiLib#19]
It seems like **CorgiLib** is interfering with the **Oh The Biomes You'll Go Mod.** Can't play without it or older version.
Or is it the other mods fault?
[crash-2023-06-16_15.14.54-fml.txt](https://github.com/CorgiTaco/CorgiLib/files/11770741/crash-2023-06-16_15.14.54-fml.txt)

**Comment by JT122406** [comment]
can you do and delete "C:\Users\Louis\curseforge\minecraft\Instances\Minievel-1.7 (1)\config\byg\trades.json5"
