### ISSUE TITLE
corgilib command not present in 1.20

### ISSUE THREAD

**Issue by Goldenlion5648** [CorgiTaco-MC/CorgiLib#26]
It appears that the command 
```/corgilib worldRegistryExport```

is not present in the 1.20 version of the mod, was this intetional? It was really useful to see the currently installed datapacks

**Comment by JT122406** [comment]
Yes it was removed

**Comment by Goldenlion5648** [comment]
Gotcha, was it difficult to keep/ maintain? It was really useful

**Comment by JT122406** [comment]
Yeah with the registry changes it was hard to keep made more sense for people to use datapacks to do it

**Comment by Goldenlion5648** [comment]
I only heard about the command from someone in discord, but my understanding was that it dumped all the data packs currently running into a folder. 

Are you saying there is another way to dump running data packs?

**Comment by JT122406** [comment]
There should be

**Comment by CorgiTaco** [comment]
@Goldenlion5648 you'll need to open the mod file with 7zip and extract the data folder for the given mod.
