### ISSUE TITLE
[macOS] Missing imgui dylib causes crash

### ISSUE THREAD

**Issue by kalkafox** [CorgiTaco-MC/CorgiLib#30]
When attempting to load CorgiLib 4.0.1.0 on macOS, the client crashes shortly before attempting to load resources. The resulting error is the imgui dylib which does not exist in the folder.

`java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/xc/y6t34tms1pv1hptzwlzrrscc0000gn/T/imgui-java-natives_1710030216506/libimgui-java64.dylib`

[crash-2024-03-09_19.23.36-client.txt](https://github.com/CorgiTaco/CorgiLib/files/14548273/crash-2024-03-09_19.23.36-client.txt)

**Comment by JT122406** [comment]
#28 fixes this
