### ISSUE TITLE
Stops sound from working

### ISSUE THREAD

**Issue by IdontPlayz343** [CorgiTaco-MC/CorgiLib#32]
Quilt 0.24.0
Minecraft 1.20.1
QFAPI 7.5.0+0.91.0-1.20.1
CorgiLib 4.0.1.1

Sounds don't play if this mod is enabled.

**Comment by ENDERZOMBI102** [comment]
also had this problem
i didn't manage to get any more information from a debugging session other than "is this mod"

how even did this happen?

**Comment by CorgiTaco** [comment]
This project has no intention of supporting Quilt. Please use the Fabric mod loader or do not use this mod at all.
