### ISSUE TITLE
Oh the Biomes we've gone beta 1.0.2 crashes with Corgilib 4.0.2.0

### ISSUE THREAD

**Issue by RoomAlex68** [CorgiTaco-MC/CorgiLib#43]
Crash log:
![crash-2024-07-31_14.04.44-client.txt](https://github.com/user-attachments/files/16450061/crash-2024-07-31_14.04.44-client.txt)

**Comment by JT122406** [comment]
Fixed in newer versions can be closed @CorgiTaco
