### ISSUE TITLE
Add announcement config

### ISSUE THREAD

**Issue by MaxWasUnavailable** [CorgiTaco-MC/CorgiLib#54]
Hi there, could we get a way to disable the GoFundMe announcement through a config option? This would be nice for modpack distribution and whatnot.

**Comment by CorgiTaco** [comment]
You'll need to make a mod and mixin and disable it then, wait for me to take down the announcement json online, or simply downgrade corgilib for the time being. It is purposely designed this way. I've made it as minimally annoying as possible and for it only appear once per client. It hides after pressing "dismiss' and never shows again for that specific user. Sorry if that comes as inconvenience but I'm using my platform best i can get to get the word out. I'd hope someone would do the same if something like that happened to me.

**Comment by Xplodin** [comment]
I cant dismiss the box on my pack, due to it overlapping a button. a config would be great for this case, other than having to enter mp menu to dismiss it

**Comment by CorgiTaco** [comment]
@Xplodin @MaxWasUnavailable Made a config to set it to display as a chat message instead if that's better. Chat message will show within 5 minutes of a player inside of a world

**Comment by Xplodin** [comment]
> @Xplodin @MaxWasUnavailable Made a config to set it to display as a chat message instead if that's better. Chat message will show within 5 minutes of a player inside of a world

thats awesome, ill send some moneys to your buddy as I just got paid
